jobs:
  test_c9s:
    name: test_9s
    runs-on: ubuntu-latest
    environment: centosduffy
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
      - with:
          python-version: '3.13'
          cache: 'pip'
      - run: printf '%s\n' "$DUFFYY_SSH_PRIVATE_KEY" > /tmp/id_centos_stream
        env:
            DUFFYY_SSH_PRIVATE_KEY:  ${{ secrets.DUFFYY_SSH_PRIVATE_KEY }}
      - run: pip install duffy fabric httpx

      - run: python t_functional_duffy_runner/src/__main__.py --arch=x86 --release=centos-9s --sshkey=/tmp/id_centos_stream --path=$GITHUB_WORKSPACE
        env:
            DUFFY_AUTH_NAME: ${{ secrets.DUFFY_AUTH_NAME }}
            DUFFY_AUTH_KEY: ${{secrets.DUFFY_AUTH_KEY}}

name: Testing
on:
 pull_request: 
    branches: [ '*' ]
 push: 
    branches: [ '*' ]
